#ifndef CLOCK_LIBS_H
#define CLOCK_LIBS_H


#include "libraries/NeoPixelBus_by_Makuna/src/NeoPixelBus.h"
#include "libraries/NeoPixelBus_by_Makuna/src/NeoPixelAnimator.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoPixelAnimator.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/DotStarAvrMethod.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/DotStarColorFeatures.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/DotStarGenericMethod.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/DotStarSpiMethod.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/Esp32_i2s.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HsbColor.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HsbColor.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HslColor.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HslColor.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HtmlColor.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HtmlColor.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HtmlColorNames.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HtmlColorNameStrings.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HtmlColorNameStrings.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/HtmlColorShortNames.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoArmMethod.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoAvrMethod.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoBitmapFile.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoBuffer.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoBufferContext.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoBufferMethods.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoColorFeatures.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoDib.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoEase.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoPixelRmtMethod.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoEspRmtMethod.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoGamma.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoGamma.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoHueBlend.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoMosaic.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoPixelAvr.c"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoPixelEsp.c"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoRingTopology.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoSpriteSheet.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoTiles.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/NeoTopology.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/RgbColor.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/RgbColor.h"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/RgbwColor.cpp"
#include "libraries/NeoPixelBus_by_Makuna/src/internal/RgbwColor.h"


#include "libraries/AsyncTCP/AsyncTCP.h"
#include "libraries/AsyncTCP/AsyncTCP.cpp"

#include "libraries/ArduinoJson/src/ArduinoJson.h"
#include "libraries/ESPAsyncWebServer/ESPAsyncWebServer.h"
#include "libraries/ESPAsyncWebServer/AsyncJson.h"
#include "libraries/ESPAsyncWebServer/WebRequest.cpp"
#include "libraries/ESPAsyncWebServer/WebServer.cpp"
#include "libraries/ESPAsyncWebServer/WebResponses.cpp"
#endif
